version: 0.2
phases:
 install:
   commands:
     - mv /usr/local/bin/docker /usr/bin/docker
     - curl -L https://raw.githubusercontent.com/docker/compose-cli/main/scripts/install/install_linux.sh | sh
 pre_build:
   commands:
     - echo Logging in to Amazon ECR...
     - echo Creating Docker Compose Context
     - export AWS_ACCESS_KEY_ID=
     - export AWS_SECRET_ACCESS_KEY=
     - docker context create ecs demoecs --from-env
     - docker context use demoecs
 build:
   commands:
     - echo Convert Compose File
     - docker --debug compose -f docker-compose.prod.yml convert > template.yml
artifacts:
  files:
    - template.yml
