version: "3.8"
services:
  insurancedb:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=sleshainsurance
    ports:
      - 3323:3306
    volumes:
      - .mysql:/var/lib/mysql
    networks:
      - sleshainsnetwork
  reverseproxy:
    container_name: proxy
    build: ./reverseproxy
    ports:
      - 3333:80
    networks:
      - sleshainsnetwork
  rediscache:
    container_name: cache
    depends_on:
      - insurancedb
    build: ./redis
    restart: on-failure
    ports:
      - 2226:6379
    networks:
      - sleshainsnetwork
  userms:
    container_name: userms
    depends_on:
      - insurancedb
    build: ./services/userms
    restart: on-failure
    ports:
      - 8888:8080
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.application.name": "userms",
        "spring.datasource.url"  : "jdbc:mysql://insurancedb:3306/sleshainsurance?useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "my-secret-pw",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"}'
    volumes:
      - .m2:/root/.m2
    networks:
      - sleshainsnetwork
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    restart: on-failure
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - sleshainsnetwork
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    restart: on-failure
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    
    networks:
      - sleshainsnetwork
  planms:
    container_name: planms
    depends_on:
      - zookeeper
    build: ./services/planms
    restart: on-failure
    ports:
      - 8889:8080
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.application.name": "planms",
        "spring.datasource.url"  : "jdbc:mysql://insurancedb:3306/sleshainsurance?useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "my-secret-pw",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "spring.cache.type":"redis",
        "spring.redis.host":"rediscache",
        "spring.redis.port":"6379",
        "configs:spring.cache.cache-names":"plan, userPlan"}'
    volumes:
      - .m2:/root/.m2
    networks:
      - sleshainsnetwork
  processms:
    container_name: processms
    depends_on:
      - planms
    build: ./services/processms
    restart: on-failure
    ports:
      - 6666:8080
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.application.name": "processms",
        "spring.datasource.url"  : "jdbc:mysql://insurancedb:3306/sleshainsurance?useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "my-secret-pw",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"}'
    volumes:
      - .m2:/root/.m2
    networks:
      - sleshainsnetwork
  sleshainsuranceui:
    container_name: ui
    depends_on:
        - userms
        - planms
        - reverseproxy
    build: ./ui/SleshaInsuranceUI
    restart: on-failure
    ports:
        - 4200:80
    networks:
      - sleshainsnetwork

networks:
  sleshainsnetwork: {}